In [10]:
import numpy as np
import pandas as pd



In [11]:
df = pd.DataFrame([[6,8,9],[7,9,9],[6,10,6],[5,12,7]], columns=['cgpa','profile_score','lpa'])
df

cgpa  profile_score  lpa
0     6              8    9
1     7              9    9
2     6             10    6
3     5             12    7

In [2]:
import tensorflow
from tensorflow import keras  
from keras import Sequential
from keras.layers import Dense


In [4]:
model = Sequential()

In [5]:
#This means: 👉 The layer has 2 neurons
model.add(Dense(2, input_dim=2, activation='linear'))
model.add(Dense(1, activation='linear'))


c:\Users\kriti\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [6]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [7]:
model.get_weights()

[array([[-0.43033993,  0.56374216],
        [ 0.26291418, -0.8734231 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.02310991],
        [0.19408596]], dtype=float32),
 array([0.], dtype=float32)]

In [12]:
new_weights = [np.array([[0.1, 0.1], [0.1, 0.1]], dtype=np.float32), np.array([0, 0], dtype=np.float32), np.array([[0.1], [0.1]], dtype=np.float32), np.array([0], dtype=np.float32)]

In [13]:
model.set_weights(new_weights)

In [14]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [15]:
optimizers = keras.optimizers.Adam(learning_rate=0.01)

In [16]:
model.compile(optimizer=optimizers, loss='mean_squared_error')

In [18]:
df['lpa'].values

array([9, 9, 6, 7])

In [19]:
model.fit(df.iloc[:, 0:-1], df['lpa'].values, epochs=75, verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 55.3677  
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 49.8187 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 43.2941 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 35.5653 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 27.6428 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 19.3975
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 13.1132 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.1393  
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.0781 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.6703 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.9402 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3.2517 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.4917 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.4723 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.9594 
Epoch 16/75
4/4 ━━━━━━━━━━

initialize weights

for epoch in range(total_epochs):

    shuffle data
    
    for batch in dataset:
    
        X_batch, Y_batch
        
        Y_pred = forward_pass(X_batch)
        
        loss = compute_loss(Y_pred, Y_batch)
        
        gradients = backprop(loss)
        
        update_weights(gradients)
        
    print(epoch_loss)


In [23]:
model.predict(np.array([[5,8]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step


array([[6.5001864]], dtype=float32)