In [ ]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[6,8,9],[7,9,9],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [3]:
df

cgpa  profile_score  lpa
0     6              8    9
1     7              9    9
2     6             10    6
3     5             12    7

In [4]:
def initialize_parameters(layer_dims):
  
  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)         

  for l in range(1, L):

    parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
      

  return parameters

In [5]:
def linear_forward(A_prev, W, b):
  
  Z = np.dot(W.T, A_prev) + b
  
  return Z

In [12]:
# Forward Prop
def L_layer_forward(X, parameters):

  A = X
  L = len(parameters) // 2                  # number of layers in the neural network
  
  for l in range(1, L+1):
    A_prev = A 
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    print("A"+str(l-1)+": ", A_prev)
    print("W"+str(l)+": ", Wl)
    print("b"+str(l)+": ", bl)
    print("--"*20)

    A = linear_forward(A_prev, Wl, bl)
    print("A"+str(l)+": ", A)
    print("**"*20)
          
  return A,A_prev

In [13]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X, parameters)

A0:  [[6]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.4]
 [1.4]]
****************************************
A1:  [[1.4]
 [1.4]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.28]]
****************************************


In [14]:
y_hat,A1

(array([[0.28]]),
 array([[1.4],
        [1.4]]))

In [15]:
parameters

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [11]:
L_layer_forward(X, parameters)

(array([[0.28]]),
 array([[1.4],
        [1.4]]))

In [16]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [17]:
update_parameters(parameters,y,y_hat,A1,X)

C:\Users\kriti\AppData\Local\Temp\ipykernel_29848\332058445.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
C:\Users\kriti\AppData\Local\Temp\ipykernel_29848\332058445.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
C:\Users\kriti\AppData\Local\Temp\ipykernel_29848\332058445.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this o

In [18]:
parameters

{'W1': array([[0.11301889, 0.11735852],
        [0.11301889, 0.11735852]]),
 'b1': array([[0.00216982],
        [0.00216982]]),
 'W2': array([[0.124416],
        [0.124416]]),
 'b2': array([[0.141856]])}

In [19]:
# Select one training example (row index = 1) from dataset

# Step 1: Extract input features (cgpa & profile_score)
# df[['cgpa', 'profile_score']] → select 2 columns as DataFrame
# .values → convert to NumPy array
# [1] → select second row (index starts at 0)
# reshape(2,1) → convert shape from (2,) to (2,1)
# Neural networks expect shape: (no_of_features, no_of_examples)
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1)


# Step 2: Extract target value (lpa)
# df[['lpa']] → select target column
# .values → convert to NumPy array
# [1] → select second row
# [0] → extract scalar from array
y = df[['lpa']].values[1][0]


# Step 3: Forward Propagation
# Pass input X through neural network
# y_hat → predicted output
# A1 → hidden layer activation (used later in backprop)
y_hat, A1 = L_layer_forward(X, parameters)


# Step 4: Convert prediction from array to scalar
# Output is shape (1,1) → [[value]]
# We extract the number for easier math operations
y_hat = y_hat[0][0]


# Step 5: Update weights and biases
# parameters → current weights
# y → actual output
# y_hat → predicted output
# A1 → hidden layer activation
# X → input features
update_parameters(parameters, y, y_hat, A1, X)


# Step 6: View updated parameters
parameters


A0:  [[7]
 [9]]
W1:  [[0.11301889 0.11735852]
 [0.11301889 0.11735852]]
b1:  [[0.00216982]
 [0.00216982]]
----------------------------------------
A1:  [[1.81047206]
 [1.87990614]]
****************************************
A1:  [[1.81047206]
 [1.87990614]]
W2:  [[0.124416]
 [0.124416]]
b2:  [[0.141856]]
----------------------------------------
A2:  [[0.60099809]]
****************************************


{'W1': array([[0.13122454, 0.14076578],
        [0.13136168, 0.14094211]]),
 'b1': array([[0.00477062],
        [0.00479021]]),
 'W2': array([[0.15482832],
        [0.15599467]]),
 'b2': array([[0.17279267]])}

In [20]:
# Step 0: Initialize network parameters (weights & biases)
# [2,2,1] → 2 input neurons, 2 hidden neurons, 1 output neuron
parameters = initialize_parameters([2,2,1])

# Number of times the model will see the entire dataset
epochs = 5

# Outer loop → controls how many times we pass through the full dataset
for i in range(epochs):

  # Store loss values for all training examples in this epoch
  Loss = []

  # Inner loop → goes through each row (training example) in dataset
  for j in range(df.shape[0]):

    # Step 1: Extract input features for j-th training example
    # Select 'cgpa' and 'profile_score'
    # Convert to numpy array
    # Pick j-th row
    # Reshape to (features, examples) = (2,1)
    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1)

    # Step 2: Extract actual output value (target)
    # Select 'lpa' column
    # Convert to numpy
    # Pick j-th row
    # Extract scalar value
    y = df[['lpa']].values[j][0]


    # Step 3: Forward Propagation
    # Pass input through neural network
    # y_hat → predicted output
    # A1 → hidden layer activation (needed for backprop)
    y_hat, A1 = L_layer_forward(X, parameters)

    # Convert prediction from array [[value]] to scalar
    y_hat = y_hat[0][0]


    # Step 4: Backpropagation & Parameter Update
    # Adjust weights based on prediction error
    update_parameters(parameters, y, y_hat, A1, X)


    # Step 5: Compute loss for this training example
    # Using Mean Squared Error
    Loss.append((y - y_hat)**2)


  # Step 6: Print average loss after each epoch
  print('Epoch - ', i+1, 'Loss - ', np.array(Loss).mean())


# Final trained weights
parameters


A0:  [[6]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.4]
 [1.4]]
****************************************
A1:  [[1.4]
 [1.4]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.28]]
****************************************
A0:  [[7]
 [9]]
W1:  [[0.11301889 0.11735852]
 [0.11301889 0.11735852]]
b1:  [[0.00216982]
 [0.00216982]]
----------------------------------------
A1:  [[1.81047206]
 [1.87990614]]
****************************************
A1:  [[1.81047206]
 [1.87990614]]
W2:  [[0.124416]
 [0.124416]]
b2:  [[0.141856]]
----------------------------------------
A2:  [[0.60099809]]
****************************************
A0:  [[ 6]
 [10]]
W1:  [[0.13122454 0.14076578]
 [0.13136168 0.14094211]]
b1:  [[0.00477062]
 [0.00479021]]
----------------------------------------
A1:  [[2.10573468]
 [2.25880601]]
****************************************
A1:  [[2.10573468]
 [2.25880601]]
W2:  [[0.15482832]
 [0.1

{'W1': array([[0.32767409, 0.42648705],
        [0.35005135, 0.45679564]]),
 'b1': array([[0.03642322],
        [0.0399399 ]]),
 'W2': array([[0.46990833],
        [0.55318347]]),
 'b2': array([[0.55145116]])}